void TextColor(int colornum) {                          //텍스트 컬러 변경
	SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE), colornum);
}
void main_menu_0() {
	printf("===================================================================================================================================================================\n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                -----------------------------------------------------------                                                           \n");
	printf("                                                |                                                         |                                                         \n");
	printf("                                                |                                                         |                                                         \n");
	printf("                                                |                      돌 강화하기                        |                                                         \n");
	printf("                                                |                                                         |                                                       \n");
	printf("                                                |                                                         |                                                         \n");
	printf("                                                -----------------------------------------------------------                                                              \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("======================================================================================================================================================================\n");

}
void difficulty_select() {
	TextColor(difficulty_color[0]);
	gotoxy(0, 25);
	printf("                 ---------------------------------------------------                  \n");
	printf("                |                                                   |                 \n");
	printf("                |                  이 지 모 드                      |                 \n");
	printf("                |                                                   |                  \n");
	printf("                |                                                   |                  \n");
	printf("                |             GSM 학생 이라면 누구나                |               \n");
	printf("                |              플레이 가능한 난이도!                |                   \n");
	printf("                |                                                   |              \n");
	printf("                |                                                   |              \n");
	printf("                |                                                   |             \n");
	printf("                 ---------------------------------------------------                \n");
	TextColor(difficulty_color[1]);
	gotoxy(70, 25);
	printf("                 ---------------------------------------------------                  \n");
	gotoxy(70, 26);
	printf("                |                                                   |                 \n");
	gotoxy(70, 27);
	printf("                |                  하 드 모 드                      |                 \n");
	gotoxy(70, 28);
	printf("                |                                                   |                  \n");
	gotoxy(70, 29);
	printf("                |                                                   |                  \n");
	gotoxy(70, 30);
	printf("                |           장애인,노약자,심신미약자는              |               \n");
	gotoxy(70, 31);
	printf("                |          이용을 삼가해 주시길 바랍니다.           |                   \n");
	gotoxy(70, 32);
	printf("                |                                                   |              \n");
	gotoxy(70, 33);
	printf("                |                                                   |              \n");
	gotoxy(70, 34);
	printf("                |                                                   |             \n");
	gotoxy(70, 35);
	printf("                 ---------------------------------------------------                \n");
	TextColor(15);
}
void main_ui_1() {
	printf("===================================================================================================================================================================\n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                     \n");
	printf("                                                         f11을 눌러 전체화면으로 설정해 주세요                                                                           \n");
	printf("                                                             화면크기에 맞춰 조절해 주세요.                                                                           \n");
	printf("                                                     이 게임은 혈압에 대하여 매우 부정적일수 있습니다.                                                                      \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                      \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                           \n");
	printf("                                                                                                                                                                        \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("======================================================================================================================================================================\n");

	
}
void main_ui_2() {
	printf("===================================================================================================================================================================\n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("               ■■■■■■■■                                                                                                                                     \n");
	printf("              ■■■■■■■■                                    ■■                                  ■■■■■                                                  \n");
	printf("             ■■■                       ■■■■■■■■       ■■                                                                                               \n");
	printf("            ■■■                       ■■■■■■■■       ■■            ■■■■             ■■■■■■■       ■■                                      \n");
	printf("           ■■■■■■■■                       ■■■       ■■                                                      ■■                                       \n");
	printf("          ■■■■■■■■                       ■■■       ■■■■       ■■■■■■                ■■■         ■■                          ■■          \n");
	printf("               ■■                             ■■■       ■■■■                                  ■■■■■      ■■         ■■■■■■■   ■■           \n");
	printf("              ■■                             ■■■       ■■               ■■■                ■■    ■■     ■■■■     ■■■■■■■   ■■            \n");
	printf("      ■■■■■■■■■■■                  ■■■       ■■              ■■■■■    ■■     ■■    ■■     ■■■■             ■■■   ■■             \n");
	printf("     ■■■■■■■■■■■                               ■■             ■■    ■■   ■■       ■■■■■     ■■                 ■■■   ■■              \n");
	printf("                                                                          ■■    ■■   ■■         ■■■       ■■                 ■■■   ■■               \n");
	printf("         ■■■■■■                             ■■■■                 ■■■■■   ■■                      ■■                 ■■■   ■■                \n");
	printf("        ■■■■■■                            ■■■■■■                ■■■     ■■■■                  ■■                          ■■                 \n");
	printf("               ■■                           ■■      ■■                 ■■     ■■■■                                                ■■                  \n");
	printf("      ■■■■■■                          ■■        ■■                ■■     ■■                                                                           \n");
	printf("     ■■■■■■                          ■■      ■■           ■■■■■■■■■■                                                                            \n");
	printf("    ■■                                   ■■■■■■                            ■■                                                                            \n");
	printf("   ■■■■■■                             ■■■■                              ■■                                                                              \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                      \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                     -----------------                                                                                                \n");
	printf("                                                                                                                                                       \n");
	printf("                                                                     -----------------                                                                                                   \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("======================================================================================================================================================================\n");
}


void main_menu_1() {
	printf("===================================================================================================================================================================\n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                -----------------------------------------------------------                                                           \n");
	printf("                                                |                                                         |                                                         \n");
	printf("                                                |                                                         |                                                         \n");
	printf("                                                |                      돌 강화하기                        |                                                         \n");                            
	printf("                                                |                                                         |                                                       \n");
	printf("                                                |                                                         |                                                         \n");
	printf("                                                -----------------------------------------------------------                                                              \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                     ■■■■                                                                    \n");
	printf("                                  ■■■■■■                                                             \n");
	printf("                                ■■■■■■                                                                            \n");
	printf("                              ■■■■■■                                                        \n");
	printf("                              ■■■■■■                                                                 \n");
	printf("                               ■■■ ■■                                                                  \n");
	printf("                                         ■■                                                          --------------------                                 \n");
	printf("                                           ■■                                                        |      store       |                                \n");
	printf("                                             ■■                                                      --------------------                         \n");
	printf("                                               ■■                                                  □■□■□■□■□■□■                            \n");
	printf("                                                 ■■                                                ■□■□■□■□■□■□                                    \n");
	printf("                      ■■■■■■■■■■■■■                                                      ■                  ■                                      \n");
	printf("                       ■■■■■■■■■■■■                                                       ■  ■■■■■■■  ■                                          \n");
	printf("                         ■■■■■■■■■                                                           ■  ■          ■  ■                                                     \n");
	printf("                       ■■■■■■■■■■■                                                         ■  ■          ■  ■                                            \n");
	printf("                      ■■■■■■■■■■■■                                                        ■ ■■■■■■■■ ■                                                      \n");
	printf("                     ■■■■■■■■■■■■■                                                       ■ ■■■■■■■■ ■                                                                   \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("======================================================================================================================================================================\n");

}
void Reinforce_ui() {
	printf("===================================================================================================================================================================\n");
	printf("                                                                                                                                                                    \n");
	printf("  돈 :                                                                                                                                      □ 메뉴                          \n");
	printf("                                                                                                                                                           \n");
	printf("  방지권 :                                                                                                                                  □ 강화                  \n");
	printf("                                                                                                                                                                 \n");
	printf("                                                                                                                                            □ 빠른 강화                       \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                            □ 판매                   \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                            □ 인벤토리                        \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                     \n");
	printf("                                                                                                                                                                             \n");
	printf("                                                                                                                                                                            \n");
	printf("                                                                                                                                                                         \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                      \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                    ------------------------------------------------------------------\n");
	printf("                                                                                                   |                                                                   \n");
	printf("                                                                                                   |------------------------------------------------------------------\n");
	printf("                                                                                                   |                                                                    \n");
	printf("                                                                                                   |                                                                    \n");
	printf("                                                                                                   |                                                                    \n");
	printf("                                                                                                   |                                                                    \n");
	printf("                                                                                                   |                                                                    \n");
	printf("                                                                                                   |                                                                    \n");
	printf("======================================================================================================================================================================\n");
}
void shop_ui_1() {
	printf("===================================================================================================================================================================\n");
	printf("                                                 ■■■■       ■      ■         ■■        ■■■■                                                                        \n");
	printf("    E X I T                                      ■             ■      ■       ■    ■      ■    ■                                                                                \n");
	printf("     (ESC)                                       ■■■■       ■■■■■       ■    ■      ■■■■                                                                                 \n");
	printf("                                                       ■       ■      ■       ■    ■      ■                                                                                     \n");
	printf("                                                 ■■■■       ■      ■         ■■        ■                                                                             \n");
	printf("===================================================================================================================================================================\n");
	printf("                                                                                                                                            \n");
	printf("                                                                                                                                                                  \n");
	printf("                                                                                                                                                 \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                       □□□                                \n");
	printf("                                                                                                                                       □□□                                \n");
	printf("                                                                                                                                       □□□                                \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                       □□□                                \n");
	printf("                                                                                                                                       □□□                               \n");
	printf("                                                                                                                                       □□□                               \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                       □□□                                \n");
	printf("                                                                                                                                       □□□                                \n");
	printf("                                                                                                                                       □□□                                \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                       next                               \n");
	printf("                                                                                                                                      -----▷                              \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("======================================================================================================================================================================\n");

}
void shop_ui_2() {
	printf("===================================================================================================================================================================\n");
	printf("                                                 ■■■■       ■      ■         ■■        ■■■■                                                                        \n");
	printf("    E X I T                                      ■             ■      ■       ■    ■      ■    ■                                                                                \n");
	printf("     (ESC)                                       ■■■■       ■■■■■       ■    ■      ■■■■                                                                                 \n");
	printf("                                                       ■       ■      ■       ■    ■      ■                                                                                     \n");
	printf("                                                 ■■■■       ■      ■         ■■        ■                                                                             \n");
	printf("===================================================================================================================================================================\n");
	printf("                                                                                                                                            \n");
	printf("                                                                                                                                                                  \n");
	printf("                                                                                                                                                 \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                       □□□                                        \n");
	printf("                                                                                                                                       □□□                                \n");
	printf("                                                                                                                                       □□□                                \n");
	printf("                                                                                                                                                                                    \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                       □□□                                \n");
	printf("                                                                                                                                       □□□                               \n");
	printf("                                                                                                                                       □□□                               \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                       □□□                                \n");
	printf("                                                                                                                                       □□□                                \n");
	printf("                                                                                                                                       □□□                                \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                       next                               \n");
	printf("                                                                                                                                      -----▷                              \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("======================================================================================================================================================================\n");

}
void soul_ui() {
	printf("===================================================================================================================================================================\n");
	printf("                                                 ■■■■       ■      ■         ■■        ■■■■                                                                        \n");
	printf("    E X I T                                      ■             ■      ■       ■    ■      ■    ■                                                                                \n");
	printf("     (ESC)                                       ■■■■       ■■■■■       ■    ■      ■■■■                                                                                 \n");
	printf("                                                       ■       ■      ■       ■    ■      ■                                                                                     \n");
	printf("                                                 ■■■■       ■      ■         ■■        ■                                                                             \n");
	printf("===================================================================================================================================================================\n");
	printf("                                                                                                                                            \n");
	printf("                                                                                                                                                                  \n");
	printf("                                                                                                                                                 \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                     \n");
	printf("                                                                                                                                                                      \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                      \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                     \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("======================================================================================================================================================================\n");

}
void fail() {
	printf("===================================================================================================================================================================\n");
	printf("   E X I T                                                                                                                                                                 \n");
	printf("    (ESC)                                                                                                                                                                 \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                     \n");
	printf("                                                                                                                                                                               \n");
	printf("                                                                                                                                                                  \n");
	printf("                                                                                                                                                                 \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                      \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                    \n");
	printf("                                                                                                                                                           \n");
	printf("                                                                                                                                                                        \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("                                                                                                                                                                       \n");
	printf("======================================================================================================================================================================\n");
}

void clear() {
	gotoxy(40, 3);
	printf("                                                        ");
	gotoxy(40, 4);
	printf("                                                        ");
	gotoxy(40, 5);
	printf("                                                        ");
	gotoxy(40, 6);
	printf("                                                        ");
	gotoxy(40, 7);
	printf("                                                        ");
	gotoxy(40, 8);    
	printf("                                                        ");
	gotoxy(40, 9);
	printf("                                                        ");
	gotoxy(40, 10);
	printf("                                                        ");
	gotoxy(40, 11);
	printf("                                                        ");
	gotoxy(40, 12);
	printf("                                                        ");
	gotoxy(40, 13);
	printf("                                                        ");
	gotoxy(40, 14);
	printf("                                                        ");
	gotoxy(40, 15);
	printf("                                                        ");
	gotoxy(40, 16);
	printf("                                                        ");
	gotoxy(40, 17);   
	printf("                                                        ");
	gotoxy(40, 18);  
	printf("                                                        ");
	gotoxy(40, 19);
	printf("                                                        ");
	gotoxy(40, 20);
	printf("                                                                         ");
	gotoxy(40, 21);                
	printf("                                                                        ");
	gotoxy(40, 22);
	printf("                                                                            ");
	gotoxy(40, 23);
	printf("                                                                             ");
	gotoxy(40, 24);
	printf("                                                                                   ");
	gotoxy(40, 25);                
	printf("                                                                          ");
}
void item() {
	gotoxy(38, 10);
	printf(" ---------------------------------------------------------------------------\n");
	gotoxy(38, 11);
	printf("|                                                                E X I T    |                                                   \n");
	gotoxy(38, 12);
	printf("|                                                                 (ESC)     |                                                 \n");
	gotoxy(38, 13);
	printf("|  □    |방지권|       :                                                   |                                                  \n");
	gotoxy(38, 14);
	printf("|                                                                           |                                              \n");
	gotoxy(38, 15);
	printf("|  □    |돌가루|       :                                                   |                                           \n");
	gotoxy(38, 16);
	printf("|                                                                           |                                          \n");
	gotoxy(38, 17);
	printf("|  □    |6강 워프석|   :                                                   |                                           \n");
	gotoxy(38, 18);
	printf("|                                                                           |                                          \n");
	gotoxy(38, 19);
	printf("|  □    |10강 워프석|  :                                                   |                                         \n");
	gotoxy(38, 20);
	printf("|                                                                           |                                       \n");
	gotoxy(38, 21);
	printf("|  □    |12강 워프석|  :                                                   |                                             \n");
	gotoxy(38, 22);
	printf("|                                                                           |                                         \n");
	gotoxy(38, 23);
	printf("|  □    |하스스톤|     :                                                   |                                           \n");
	gotoxy(38, 24);
	printf("|                                                                           |                                   \n");
	gotoxy(38, 25);
	printf("|                                                                           |                                    \n");
	gotoxy(38, 26);
	printf(" ---------------------------------------------------------------------------                                    \n");


}